// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnvVar = (keys: string[]): string => {
  for (const key of keys) {
    const value = import.meta.env[key];
    if (value && typeof value === 'string') return value.trim();
  }
  return '';
};

// URL sanitization to remove trailing slashes and spaces
let SUPABASE_URL = getEnvVar(['VITE_SUPABASE_URL']);
if (SUPABASE_URL.endsWith('/')) {
  SUPABASE_URL = SUPABASE_URL.slice(0, -1);
}

// Checking both keys for fallback
const SUPABASE_KEY = getEnvVar(['VITE_SUPABASE_ANON_KEY', 'VITE_SUPABASE_PUBLISHABLE_KEY']);

if (!SUPABASE_URL) {
  console.error('🚨 [Supabase] URL is undefined! Please set VITE_SUPABASE_URL in your .env file.');
}
if (!SUPABASE_KEY) {
  console.error('🚨 [Supabase] Key is undefined! Please set VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.');
}

// Verificar e limpar sessões expiradas ANTES de criar o cliente
// para evitar travamento no refresh de token
try {
  const sbKeys = Object.keys(localStorage).filter(
    (k) => k.startsWith('sb-') && k.endsWith('-auth-token')
  );
  for (const key of sbKeys) {
    const raw = localStorage.getItem(key);
    if (raw) {
      const parsed = JSON.parse(raw);
      const expiresAt = parsed?.expires_at;
      if (expiresAt && Date.now() / 1000 > expiresAt + 60) {
        // Token expirado há mais de 60 segundos - remover para evitar travamento
        console.warn('[client] Removing expired Supabase session from localStorage');
        localStorage.removeItem(key);
      }
    }
  }
} catch (_) {}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
