// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnvVar = (keys: string[]): string => {
  for (const key of keys) {
    const value = import.meta.env[key];
    if (value && typeof value === 'string') return value.trim();
  }
  return '';
};

const DEFAULT_SUPABASE_URL = "https://kubfzjfjvovbdlqchhgh.supabase.co";
const DEFAULT_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YmZ6amZqdm92YmRscWNoaGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTkzMzgsImV4cCI6MjA4OTUzNTMzOH0.5hgkP6ges3FyMwvmgEZMDFzVNwksNP-l6moUkm8jmvc";

// URL sanitization to remove trailing slashes and spaces
export let SUPABASE_URL = getEnvVar(['VITE_SUPABASE_URL']) || DEFAULT_SUPABASE_URL;
if (SUPABASE_URL.endsWith('/')) {
  SUPABASE_URL = SUPABASE_URL.slice(0, -1);
}

// Checking keys with fallback to production default
export const SUPABASE_KEY = getEnvVar(['VITE_SUPABASE_ANON_KEY', 'VITE_SUPABASE_PUBLISHABLE_KEY']) || DEFAULT_SUPABASE_KEY;

console.log('[Supabase Client] Connected to:', SUPABASE_URL);

// Verificar e limpar sessões expiradas ANTES de criar o cliente
// para evitar travamento no refresh de token
try {
  const sbKeys = Object.keys(localStorage).filter(
    (k) => k.startsWith('sb-') && k.endsWith('-auth-token')
  );
  for (const key of sbKeys) {
    const raw = localStorage.getItem(key);
    if (raw) {
      const parsed = JSON.parse(raw);
      const expiresAt = parsed?.expires_at;
      if (expiresAt && Date.now() / 1000 > expiresAt + 60) {
        // Token expirado há mais de 60 segundos - remover para evitar travamento
        console.warn('[client] Removing expired Supabase session from localStorage');
        localStorage.removeItem(key);
      }
    }
  }
} catch (_) {}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
